name: run-tests
description: "Runs tests."

runs:
  using: composite
  steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "8.0.x"

    - name: Install NBGV
      run: dotnet tool install -g nbgv
      shell: bash

    - name: Restore dependencies
      run: dotnet restore
      shell: bash

    - name: Build project
      run: dotnet build --configuration Release --no-restore
      shell: bash

    - name: Run tests
      run: dotnet test --no-restore --configuration Release --logger trx
      shell: bash
