name: Publish on push to Master.

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Call Composite Action
        uses: ./.github/actions/run-tests
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
